#ifndef MQTT_FILAMENT_DRYER_WT32_ETH01_FILAMENT_DRYER_FAN_STATES_ENUM_H
#define MQTT_FILAMENT_DRYER_WT32_ETH01_FILAMENT_DRYER_FAN_STATES_ENUM_H


enum FanStates
{
    FanUninitialized,
    FanAlwaysOn,
    FanOnAutomatically,
    FanAlwaysOff
};


#endif //MQTT_FILAMENT_DRYER_WT32_ETH01_FILAMENT_DRYER_FAN_STATES_ENUM_H
