#ifndef MQTT_THERMOSTAT_WT32_ETH01_THERMOSTAT_TEMPERATURE_CHANGE_STATE_ENUM_H
#define MQTT_THERMOSTAT_WT32_ETH01_THERMOSTAT_TEMPERATURE_CHANGE_STATE_ENUM_H


enum ThermostatModeStates
{
    ModeUninitialized,
    ModeOff,
    ModeCooling,
    ModeMaintainingRange,
    ModeHeating
};


#endif //MQTT_THERMOSTAT_WT32_ETH01_THERMOSTAT_TEMPERATURE_CHANGE_STATE_ENUM_H
