#ifndef MQTT_FILAMENT_DRYER_WT32_ETH01_FILAMENT_DRYER_TEMPERATURE_CHANGE_STATE_ENUM_H
#define MQTT_FILAMENT_DRYER_WT32_ETH01_FILAMENT_DRYER_TEMPERATURE_CHANGE_STATE_ENUM_H


enum ThermostatModeStates
{
    ModeUninitialized,
    ModeOff,
    ModeCooling,
    ModeMaintainingRange,
    ModeHeating
};


#endif //MQTT_FILAMENT_DRYER_WT32_ETH01_FILAMENT_DRYER_TEMPERATURE_CHANGE_STATE_ENUM_H
